mp.messaging.incoming.words-in.auto.offset.reset=earliest
mp.messaging.incoming.words-in.topic=words
mp.messaging.outgoing.words-out.topic=words

quarkus.datasource.db-kind=mysql
quarkus.datasource.devservices.image-name=mysql:9.5
quarkus.datasource.devservices.port=41827
quarkus.datasource.devservices.db-name=quarkus
quarkus.datasource.devservices.username=quarkus
quarkus.datasource.devservices.password=quarkus